name: Slither Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze_contract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install slither-analyzer

    - name: Analyze Contract
      run: |
        slither contracts/GasChecker.sol --json report.json

    - name: Save Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Slither Report
        path: |
          report.json

    
